[package]
name = "rtee"
version = "0.1.0"
edition = "2021"
authors = ["Jérôme Chételat <jerome.chetelat@hesge.ch>"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
anyhow = "1.0.75"
pest = "2.7.4"
pest_derive = "2.7.4"

